import {
  type Message,
  createDataStreamResponse,
  smoothStream,
  streamText,
} from 'ai';

import { auth } from '@/app/(auth)/auth';
import { openaiModel } from '@/lib/ai';
import { models } from '@/lib/ai/models';
import { systemPrompt } from '@/lib/ai/prompts';
import {
  deleteChatById,
  getChatById,
  saveChat,
  saveMessages,
} from '@/lib/db/queries';
import {
  generateUUID,
  getMostRecentUserMessage,
  sanitizeResponseMessages,
} from '@/lib/utils';

import { generateTitleFromUserMessage } from '../../actions';
import { createDocument } from '@/lib/ai/tools/create-document';
import { updateDocument } from '@/lib/ai/tools/update-document';
import { requestSuggestions } from '@/lib/ai/tools/request-suggestions';
import { getWeather } from '@/lib/ai/tools/get-weather';

export const maxDuration = 60;

type AllowedTools =
  | 'createDocument'
  | 'updateDocument'
  | 'requestSuggestions'
  | 'getWeather';

const blocksTools: AllowedTools[] = [
  'createDocument',
  'updateDocument',
  'requestSuggestions',
];

const weatherTools: AllowedTools[] = ['getWeather'];
const allTools: AllowedTools[] = [...blocksTools, ...weatherTools];

/**
 * POST handler for the chat API. This endpoint:
 * - Validates the session and user authentication.
 * - Checks the provided model identifier and user message.
 * - Creates a new chat if it does not exist.
 * - Saves the user message.
 * - Streams the response generated by the AI.
 */
export async function POST(request: Request) {
  // Parse the JSON body to extract chat ID, messages, and model ID.
  const {
    id,
    messages,
    modelId,
  }: { id: string; messages: Array<Message>; modelId: string } =
    await request.json();

  // Check the authentication session and user.
  const session = await auth();

  if (!session || !session.user || !session.user.id) {
    // Stop if the user is not authenticated.
    return new Response('Unauthorized', { status: 401 });
  }

  // Get the model configuration based on the given modelId.
  const model = models.find((model) => model.id === modelId);

  if (!model) {
    // Return an error if the model is not found.
    return new Response('Model not found', { status: 404 });
  }

  // Extract the most recent message from the user.
  const userMessage = getMostRecentUserMessage(messages);

  if (!userMessage) {
    // Respond with a bad request error if there is no user message.
    return new Response('No user message found', { status: 400 });
  }

  // Check for an existing chat in the database using the provided chat ID.
  const chat = await getChatById({ id });

  if (!chat) {
    // When chat does not exist, generate a title using the user message.
    const title = await generateTitleFromUserMessage({ message: userMessage });
    // Save the new chat with the generated title.
    await saveChat({ id, userId: session.user.id, title });
  }

  // Save the incoming user message in the database.
  await saveMessages({
    messages: [{
      ...userMessage,
      createdAt: new Date(),
      chatId: id,
    }],
  });

  // Create a streaming response using the AI function.
  return createDataStreamResponse({
    execute: (dataStream) => {
      // Stream the response text from the AI engine.
      const result = streamText({
        model: openaiModel(model.apiIdentifier),
        system: systemPrompt,
        messages,
        maxSteps: 5,
        experimental_activeTools: allTools,
        experimental_transform: smoothStream({ chunking: 'word' }),
        experimental_generateMessageId: generateUUID,
        tools: {
          // Tool integration for real-time actions.
          getWeather,
          createDocument: createDocument({ session, dataStream, model }),
          updateDocument: updateDocument({ session, dataStream, model }),
          requestSuggestions: requestSuggestions({ session, dataStream, model }),
        },
        onFinish: async ({ response }) => {
          // When AI generation is finished, save generated messages
          // after sanitizing out any incomplete tool calls.
          if (session.user?.id) {
            try {
              const responseMessagesWithoutIncompleteToolCalls =
                sanitizeResponseMessages(response.messages);

              await saveMessages({
                messages: responseMessagesWithoutIncompleteToolCalls.map(
                  (message) => {
                    return {
                      id: message.id,
                      chatId: id,
                      role: message.role,
                      content: message.content,
                      createdAt: new Date(),
                    };
                  },
                ),
              });
            } catch (error) {
              // Log an error if saving messages fails.
              console.error('Failed to save chat');
            }
          }
        },
        experimental_telemetry: {
          isEnabled: true,
          functionId: 'stream-text',
        },
      });

      // Merge the AI's streaming result into the HTTP data stream.
      result.mergeIntoDataStream(dataStream);
    },
  });
}

/**
 * DELETE handler for the chat API.
 * This endpoint allows authenticated users to delete a chat
 * if they own it.
 */
export async function DELETE(request: Request) {
  const { searchParams } = new URL(request.url);
  const id = searchParams.get('id');

  if (!id) {
    return new Response('Not Found', { status: 404 });
  }

  const session = await auth();

  if (!session || !session.user) {
    return new Response('Unauthorized', { status: 401 });
  }

  try {
    const chat = await getChatById({ id });

    if (chat.userId !== session.user.id) {
      return new Response('Unauthorized', { status: 401 });
    }

    await deleteChatById({ id });

    return new Response('Chat deleted', { status: 200 });
  } catch (error) {
    return new Response('An error occurred while processing your request', {
      status: 500,
    });
  }
}
